Bandas/FACEBAND.WEB/Controllers/BandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using System.Globalization;

using FACEBAND.WEB.Helpers;
using FACEBAND.WEB.Models;
using FACEBAND.WEB.ViewModel.Band;
using FACEBAND.WEB.Filters;
using System.IO;

namespace FACEBAND.WEB.Controllers
{
    public class BandController : BaseController
    {
        [AppAuthorize(AppRol.Usuario)]
        public ActionResult Index()
        {
            var viewModel = new BandViewModel();
            viewModel.CargarDatos(CargarDatosContext(),Session.GetUsuarioId());
            return View(viewModel);
        }

        [AppAuthorize(AppRol.Usuario)]
        public ActionResult _AddMensajeBanda (int BandaId)
        {
            var viewModel = new _AddMensajeBandaViewModel();
            viewModel.CargarDatos(Session.GetUsuarioId(),BandaId);
            return PartialView(viewModel);
        }

        [HttpPost]
        [AppAuthorize(AppRol.Usuario)]
        public ActionResult _AddMensajeBanda(_AddMensajeBandaViewModel model)
        {
            try
            {
                using (var TransactionScope = new TransactionScope())
                {
                    var objMensaje = new MensajeBanda();

                    objMensaje.BandaId = model.BandaId;
                    objMensaje.Mensaje = model.Mensaje;
                    objMensaje.Fecha = DateTime.Now;
                    objMensaje.UsuarioId = Session.GetUsuarioId();
                    objMensaje.Estado = ConstantHelpers.ESTADO_ACTIVO;
                    context.MensajeBanda.Add(objMensaje);
                    context.SaveChanges();
                    TransactionScope.Complete();

                    return RedirectToAction("Index");
                }

            }catch(Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [AppAuthorize(AppRol.Usuario)]
        public ActionResult EditBanda (int bandaId)
        {
            var viewModel = new EditBandaViewModel();
            viewModel.CargarDatos(CargarDatosContext(),bandaId);
            return View(viewModel);
        }

        [HttpPost]
        [AppAuthorize(AppRol.Usuario)]
        public ActionResult EditBanda(EditBandaViewModel model)
        {
            try
            {
                using (var TransactionScope = new TransactionScope())
                {
                    var objBanda = context.Banda.FirstOrDefault(x => x.BandaId == model.BandaId);

                    objBanda.Nombre = model.Nombre;
                    objBanda.Descripcion = model.Descripcion;

                    if (model.Foto != null)
                    {
                        String extension = Path.GetExtension(model.Foto.FileName);
                        String NombreFoto = "IMG" + "_" + model.BandaId + "_" + DateTime.Now.Ticks + extension;
                        String path = Path.Combine(Server.MapPath(ConstantHelpers.PATH_IMG_PERFIL), NombreFoto);
                        model.Foto.SaveAs(path);
                        objBanda.Foto = ConstantHelpers.PATH_IMG_PERFIL_db + "/" + NombreFoto;
                    }

                    if(model.LstSelect != null)
                    {
                        foreach (var item in model.LstSelect)
                        {
                            var objGeneroBanda = new GeneroBanda();

                            objGeneroBanda.BandaId = model.BandaId;
                            objGeneroBanda.GeneroId = item;
                            objGeneroBanda.Estado = ConstantHelpers.ESTADO_ACTIVO;
                            context.GeneroBanda.Add(objGeneroBanda);
                        }
                    }
                    

                    context.SaveChanges();
                    TransactionScope.Complete();

                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [AppAuthorize(AppRol.Usuario)]
        public ActionResult DeleteUserBand(Int32 usuarioId)
        {
            try
            {
                using (var TransactionScope = new TransactionScope())
                {
                    var objusuario = context.UsuarioBanda.FirstOrDefault(x => x.UsuarioId == usuarioId);

                    //objusuario.Estado = ConstantHelpers.ESTADO_INACTIVO;
                    context.UsuarioBanda.Remove(objusuario);
                    context.SaveChanges();
                    TransactionScope.Complete();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        [AppAuthorize(AppRol.Usuario)]
        public ActionResult _AddUserBand(int BandaId, Int32? usuarioId)
        {
            if(usuarioId.HasValue)
            {
                try
                {
                    using (var TransactionScope = new TransactionScope())
                    {
                        var objusuario = new UsuarioBanda();

                        objusuario.UsuarioId = usuarioId.Value;
                        objusuario.BandaId = BandaId;
                        objusuario.Rol = "BAT";
                        objusuario.FechaIngreso = DateTime.Now;
                        objusuario.Estado = ConstantHelpers.ESTADO_ACTIVO;
                        context.UsuarioBanda.Add(objusuario);
                        context.SaveChanges();
                        TransactionScope.Complete();
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                var viewModel = new _AddUserBandViewModel();
                viewModel.CargarDatos(CargarDatosContext(), BandaId);
                return PartialView(viewModel);
            }
            
        }

    }
}

Bandas/FACEBAND.WEB/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using FACEBAND.WEB.Helpers;
using FACEBAND.WEB.Models;
using FACEBAND.WEB.ViewModel.User;
using FACEBAND.WEB.Filters;

namespace FACEBAND.WEB.Controllers
{
    public class UserController : BaseController
    {
        [AppAuthorize(AppRol.Usuario)]
        public ActionResult Index(IndexViewModel model)
        {
            model.CargarDatos(CargarDatosContext());
            return View(model);
        }
    }
}

Bandas/FACEBAND.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="app">

<head>
    <meta charset="utf-8" />
    <title>FACEBAND @(ViewBag.Title != null ? @ViewBag.Title : "")</title>
    <meta name="description" content="FACE BAND" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    @RazorHelpers.Style("js/jPlayer/jplayer.flat.css", Url)
    @RazorHelpers.Style("css/app.v1.css", Url)
    @RazorHelpers.Style("js/chosen/chosen.css", Url)
    
</head>

<body class="">

    <section class="vbox">
        <header class="bg-white-only header header-md navbar navbar-fixed-top-xs">
            <div class="navbar-header aside bg-info dk @(ViewBag.Collapse == true ? "nav-xs" : "")"> <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html"> <i class="icon-list"></i> </a> <a href="@Url.Action("Index","User")" class="navbar-brand text-lt"> <i class="icon-earphones"></i> <img src="@Url.Content("images/logo.png") alt=" ." class="hide"> <span class="hidden-nav-xs m-l-sm">FACEBAND</span> </a> <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user"> <i class="icon-settings"></i> </a> </div>
            <ul class="nav navbar-nav hidden-xs">
                <li> <a href="#nav,.navbar-header" data-toggle="class:nav-xs,nav-xs" class="text-muted"> <i class="fa fa-indent text"></i> <i class="fa fa-dedent text-active"></i> </a> </li>
            </ul>
            <form class="navbar-form navbar-left input-s-lg m-t m-l-n-xs hidden-xs" role="search">
                <div class="form-group">
                    <div class="input-group"> <span class="input-group-btn"> <button type="submit" class="btn btn-sm bg-white btn-icon rounded"><i class="fa fa-search"></i></button> </span> <input type="text" class="form-control input-sm no-border rounded" placeholder="Buscar ..."> </div>
                </div>
            </form>
            <div class="navbar-right ">
                <ul class="nav navbar-nav m-n hidden-xs nav-user user">
                    <li class="hidden-xs">
                        <a href="#" class="dropdown-toggle lt" data-toggle="dropdown"> <i class="icon-bell"></i> <span class="badge badge-sm up bg-danger count">2</span> </a>
                        <section class="dropdown-menu aside-xl animated fadeInUp">
                            <section class="panel bg-white">
                                <div class="panel-heading b-light bg-light"> <strong>You have <span class="count">2</span> notifications</strong> </div>
                                <div class="list-group list-group-alt">
                                    <a href="#" class="media list-group-item">
                                        <span class="pull-left thumb-sm">
                                            <img src="@Url.Content(Session.GetFoto())" alt="..." class="img-circle">
                                        </span>
                                        <span class="media-body block m-b-none"> Use awesome animate.css<br> <small class="text-muted">10 minutes ago</small> </span>
                                    </a>
                                    <a href="#" class="media list-group-item">
                                        <span class="media-body block m-b-none"> 1.0 initial released<br> <small class="text-muted">1 hour ago</small> </span>
                                    </a>
                                </div>
                                <div class="panel-footer text-sm"> <a href="#" class="pull-right"><i class="fa fa-cog"></i></a> <a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a> </div>
                            </section>
                        </section>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle bg clear" data-toggle="dropdown">
                            <span class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm">
                                <img src="@Url.Content(@Session.GetFoto())" alt="...">
                            </span>@Session.GetNombreCompleto() <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight">
                            <li> <span class="arrow top hidden-nav-xs"></span> <a href="#">Opciones</a> </li>
                            <li> <a href="profile.html">Perfil</a> </li>
                            <li> <a href="#"> <span class="badge bg-danger pull-right">3</span> Notificaciones </a> </li>
                            <li class="divider"></li>
                            <li> <a href="@Url.Action("Logout", "Home")" data-toggle="ajaxModal">Cerrar Sesión</a> </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </header>
        <section>
            <section class="hbox stretch">

                @RenderPage("~/Views/Shared/_Sidebar.cshtml")

                @RenderBody()
            </section>
        </section>
    </section>

    <div class="row-fluid" id="default-modal-container">
        <div class="hide" id="default-modal-loading">
            <div class="modal-body">
                <h3>
                    <i class="fa fa-spinner fa fa-spin fa fa-large"></i>&nbsp;Cargando...
                </h3>
            </div>
        </div>
        <div class="hide" id="default-modal-loading-error">
            <div class="modal-body">
                <h3>
                    <i class="fa-warning"></i>&nbsp;Ha ocurrido un error
                </h3>
            </div>
        </div>
    </div>
    
    
    @RazorHelpers.Content("js/app.v1.js", Url)
    @RazorHelpers.Content("js/app.plugin.js", Url)
    @RazorHelpers.Content("js/jPlayer/jquery.jplayer.min.js", Url)
    @RazorHelpers.Content("js/jPlayer/add-on/jplayer.playlist.min.js", Url)
    @RazorHelpers.Content("js/jPlayer/demo.js", Url)
    @RazorHelpers.Content("js/chosen/chosen.jquery.min.js", Url)
    @RazorHelpers.Content("js/file-input/bootstrap-filestyle.min.js", Url)
    @RazorHelpers.Content("js/datepicker/bootstrap-datepicker.js", Url)
    @RazorHelpers.Script("Pages/Shared/Global.js", Url)
    
    

</body>
<!-- Mirrored from flatfull.com/themes/musik/genres.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Apr 2016 03:10:59 GMT -->
</html>

Bandas/FACEBAND.WEB/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en" class="bg-info">

<head>
    <meta charset="utf-8" />
    <title>FACEBAND @(ViewBag.Title != null ? @ViewBag.Title : "")</title>
    <meta name="description" content="FACE BAND" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    @RazorHelpers.Style("js/jPlayer/jplayer.flat.css", Url)
    @RazorHelpers.Style("css/app.v1.css", Url)
    
</head>
<body class="bg-info">
    <section id="content" class="m-t-lg wrapper-md animated fadeInUp">
        @RenderBody()
    </section>
    <br/><br /><br /><br /><br />
    <!-- footer -->
    <footer id="footer">
        <div class="text-center padder">
            <p> <small>Web app by Pedro, Harold y Joseph<br>&copy; @DateTime.Now.Year</small> </p>
        </div>
    </footer>
    <!-- / footer --> <!-- Bootstrap --> <!-- App -->

    @RazorHelpers.Content("js/app.v1.js",Url)
    @RazorHelpers.Content("js/app.plugin.js", Url)
    @RazorHelpers.Content("js/jPlayer/jquery.jplayer.min.js", Url)
    @RazorHelpers.Content("js/jPlayer/add-on/jplayer.playlist.min.js", Url)
    @RazorHelpers.Content("js/jPlayer/demo.js", Url)

</body>

</html>

Bandas/FACEBAND.WEB/Views/Shared/_ModalLayout.cshtml
@{
    ViewBag.GUID = ViewBag.GUID ?? Guid.NewGuid().ToString();
    
    var hasModalForm = ViewBag.Form != null && ViewBag.Form is ModalFormHelpers;
    var hasAjaxModalForm = ViewBag.Form != null && ViewBag.Form is ModalAjaxFormHelpers;
    
    if (hasAjaxModalForm && String.IsNullOrEmpty(ViewBag.Form.AjaxOptions.UpdateTargetId))
    {
        ViewBag.Form.AjaxOptions.UpdateTargetId = ViewBag.GUID;
    }
}

@if (ViewBag.ModalSize != null)
{
    <script id="modal-size-@ViewBag.GUID">

        $('#modal-size-@ViewBag.GUID').closest('.modal-dialog').addClass('modal-@ViewBag.ModalSize');
    </script>
}

<div id=@ViewBag.GUID>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">
            @if (ViewBag.Icon != null)
            {
                <i class="@ViewBag.Icon contrast">&nbsp;</i> 
            }
            @ViewBag.Title
        </h4>
    </div>

    @MessageHelpers.ShowMessages(TempData, "margin-bottom: 0px;")


    @if (hasModalForm)
    {
        <text>@{ViewBag.Form.BeginForm(Html);}</text>
    }
    else if (hasAjaxModalForm)
    {
        <text>@{ViewBag.Form.BeginForm(Ajax);}</text>
    }

    <div class="modal-body">
        @RenderBody()
    </div>

    <div class="modal-footer">
        @RenderSection("Footer", false)
        @if (ViewBag.DeshabilitarCerrarFooter == null || !ViewBag.DeshabilitarCerrarFooter)
        { 
            <button class="btn " data-dismiss="modal"><i class="icon-cancel-circle2 position-left"></i> Cancelar</button>
        }    
        
    </div>

    @if (ViewBag.Form != null || ViewBag.AjaxForm != null)
    {
        Html.EndForm();
    }

</div>
   

<script id="rebind-jquery-@ViewBag.GUID">

    RebindJquery($('#rebind-jquery-@ViewBag.GUID').closest('.modal'));

</script>


@RenderSection("Scripts", false)

Bandas/FACEBAND.WEB/Views/Shared/_PermisoInsuficienteModal.cshtml

@{
    Layout = ConstantHelpers.Layout.MODAL_LAYOUT_PATH;
    ViewBag.Title = "Permisos insuficientes";
}

    <div class="alert alert-danger" style="text-align: center;">
        <h4> <i class="icon-remove-sign"></i> No tiene los permisos necesarios.</h4>
        <br />
        Para solicitar el permiso correspondiente debe comunicarse con el administrador del sistema.
    </div>

@section Footer{

}

Bandas/FACEBAND.WEB/Views/Shared/_Sidebar.cshtml
<aside class="bg-black dk  aside hidden-print @(ViewBag.Collapse == true ? "nav-xs" : "")" id="nav">
    <section class="vbox">
        <section class="w-f-md scrollable">
            <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railopacity="0.2">
                <!-- nav -->
                <nav class="nav-primary hidden-xs">
                    @switch (Session.GetRol())
                    {
                        case AppRol.Administrador:
                            {
                                <ul class="nav bg clearfix">
                                    <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"> Opciones </li>
                                    <li class="@(ViewBag.Section == "Bandas" ? "active" : "")"> <a href="index.html"> <i class="icon-disc icon text-success"></i> <span class="font-bold">Bandas</span> </a> </li>
                                    <li class="@(ViewBag.Section == "Generos" ? "active" : "")"> <a href="genres.html"> <i class="icon-list icon text-info"></i> <span class="font-bold">Géneros</span> </a> </li>
                                    <li class="@(ViewBag.Section == "Usuarios" ? "active" : "")"> <a href="events.html"> <i class="icon-user icon text-primary-lter"></i> <span class="font-bold">Usuarios</span> </a> </li>
                                    <li class="@(ViewBag.Section == "Mensajes" ? "active" : "")"> <a href="listen.html"> <i class="icon-drawer icon text-danger-dk"></i> <span class="font-bold">Mensajes</span> </a> </li>
                                    <li class="m-b hidden-nav-xs"></li>
                                </ul>
                                
                        break;
                        }
                        case AppRol.Usuario:
                        {
                        <ul class="nav bg clearfix">
                            <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"> Opciones </li>
                            <li class="@(ViewBag.Section == "Bandas" ? "active" : "")"> <a href="@Url.Action("Index","User")"> <i class="icon-disc icon text-success "></i> <span class="font-bold">Bandas</span> </a> </li>
                            <li class="@(ViewBag.Section == "TopList" ? "active" : "")"> <a href="events.html"> <i class="icon-equalizer icon text-info"></i> @*<b class="badge bg-primary pull-right">6</b>*@ <span class="font-bold">Top List</span> </a> </li>
                            <li class="@(ViewBag.Section == "Videos" ? "active" : "")"> <a href="listen.html"> <i class="icon-screen-desktop icon text-primary-lter"></i> <span class="font-bold">Videos</span> </a> </li>
                            <li class="@(ViewBag.Section == "Dashboard" ? "active" : "")"> <a href="video.html" data-target="#content" data-el="#bjax-el" data-replace="true"> <i class="icon-social-youtube icon text-primary"></i> <span class="font-bold">Video</span> </a> </li>
                            <li class="m-b hidden-nav-xs"></li>
                        </ul>
                        
                        <ul class="nav" data-ride="collapse">
                            @if (ViewBag.Section == "Bandas")
                            {
                                <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"> Opciones Extra</li>
                                <li> <a href="@Url.Action("Index","Band")"> <i class="icon-music-tone icon"></i> <span>Mi Banda</span> </a> </li>
                            }
                        </ul>
                        break;
                        }
                    }
                </nav>
                <!-- / nav -->
            </div>
        </section>
        <footer class="footer hidden-xs no-padder text-center-nav-xs">
            <div class="bg hidden-xs ">
                <div class="dropdown dropup wrapper-sm clearfix">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="thumb-sm avatar pull-left m-l-xs">
                            <img src="@Url.Content(@Session.GetFoto())" class="dker" alt="...">
                            <i class="on b-black"></i>
                        </span>
                        <span class="hidden-nav-xs clear">
                            <span class="block m-l">
                                <strong class="font-bold text-lt">@Session.GetNombreCompleto()</strong> <b class="caret"></b>
                            </span>
                            <span class="text-muted text-xs block m-l">@(Session.GetRolCompleto() == ConstantHelpers.ROL_USUARIO ? "" : "Administrador")</span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight aside text-left">
                        <li> <span class="arrow bottom hidden-nav-xs"></span> <a href="#">Opciones</a> </li>
                        <li> <a href="profile.html">Perfil</a> </li>
                        <li> <a href="#"> <span class="badge bg-danger pull-right">3</span> Notificaciones </a> </li>
                        <li class="divider"></li>
                        <li> <a href="modal.lockme.html" data-toggle="ajaxModal">Cerrar Sesión</a> </li>
                    </ul>
                </div>
            </div>
        </footer>
    </section>
</aside>